/* includes/HsSDLConfig.h.  Generated by configure.  */
/* includes/HsSDLConfig.h.in.  Generated from configure.ac by autoheader.  */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "lemmih@gmail.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Haskell SDL package"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Haskell SDL package 0.1.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "SDL-ttf"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.1.0"
